### ISSUE TITLE
Dispatch tasks

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#53]
### Overview

The task manager is the subcomponent responsible for executing workflow tasks. It's responsible for triggering the task plug-ins, mapping input and output, providing meta data and updating meta data, updating task status, and notifying the workflow manager after a task has been completed.

This task is concerned with the initial basic functionality of dispatching a task that has been added to the queue. Please see the following tickets for additional functionality:

- #47 
- #50 

### Dispatching tasks
Tasks are picked up from a queue in a RabbitMQ.
Queue name: md.tasks.dispatch
Event schema: 

```
{
  "ExecutionId": $execution_id,
  "WorkflowInstanceId": $workflow_instance_id,
  "StorageInformation": Object
}
```

Additional task information is then retrieved from MongoDB based on the workflow instance ID and the execution ID.

#### Handling a task

1. Retrieve task information from MongoDB
2. Check the task type and instantiate the relevant plug-in
3. Provide the following information to the specific plug-in:
    1. Artifact dictionary
    2. The `task_plugin_arguments` property in the task's object in MongoDB 
    3. Storage engine credentials
    5. Output directory path
4. Call the plug-in's "run" method
5. Update task status in MongoDB to submitted
6. Acknowledge the task dispatch event so that it is removed from RabbitMQ

#### Plug-in errors
A plug-in can fail either because the event doesn't contain the information it needs, or because of an external reason such as an app server not being available. To facilitate error handling plug-in should be able to raise one of the following exceptions:

- InvalidTask: to be used when the task does not contain the necessary information, for example when the task plug-in arguments don't contain the required fields for that plug-in
- UpstreamError: to be used when a plug-in can communicate with an external system.

### Acceptance criteria

- Given a valid event in RabbitMQ, when it is picked up by the event broker adapter it should trigger the task executer
- Given an event doesn't include all of the required information, when it is picked up by the event broker adapter it should be rejected with requeue=false
- Given an event references a non-existent task, when it is picked up it should be rejected with requeue=false
- When the plug-in throws an upstream error exception, the message should be rejected with requeue=true
- When the plug-in throws an invalid event exception, the message should be rejected with requeue=false

**Comment by mocsharp** [comment]
Here's a rough idea of how the **Clinical Workflow Manager** (CWM) & **Task Manager** (TM) would work together:

**Clinical Workflow Manager** - workflow for requesting a task to be done:
- Publishes task requests for `md.task.request.{plugin-name}` to the Task Exchange 
- Creates a Task Payload (TP) (maybe a bucket?) for the task to access (a few options)
  - A single TP for R&W of input and output data
  - A read-only input plus and writable output

**Task Manager**:
- Subscribes to `md.task.request.*` to capture all task request events.
- Decides how incoming requests are scheduled based on some configurations provided by each plugin. E.g. number of concurrent jobs allowed. Or based on the resource required by each task and the available resources provided _by the plugin_. (A TaskFactory that the plugin implements) -- (Another option is to offload scheduling to the plugin)
- Each plugin registers a specific topic with the Task Manager. E.g. `md.task.request.argo`

When TM receives a task request:
- Retrieves data from TP 
- Makes data in TP available to the request (could be an HTTP upload or mapping a local volume to Argo)
- Executes the task
- Monitors the status of the task, which can be implemented in a few ways:
  - Event-driven
  - Callback (RESTful API)
  - Polling
- Notifies task manager upon completion of the task


The abstract (base) class of the TaskPlugin may look like this:

```python
class TaskBase(metaclass = ABCMeta)
   @abstractmethod
   def register(self, topic):
      """ registers the plugin and subscribes to task requests for the 
      specified topic.
      """
      pass
   
   @property
   @abstractmethod
   def payload(self):
      """ access to the payload metadata: location, filenames, etc...
      """
      pass
   
   @abstractmethod
   def complete(self, task_id, delivery_tag, status, results):
      """ completes a task, sends a `md.task.complete` message with final status and results (structure to be defined)
      """
      pass

```

**Comment by joshliberty** [comment]
When we discussed it a few weeks ago, this was one of the arguments for keeping them in the same process- because they will be coupled anyway by using the same database.

The task executer also needs to update the task status and power the task API- things will get noticeably more complex if we try to maintain two databases for that. I think we can do that in the future, when we really separate them- for now it feels like premature optimisation to me.

**Comment by mocsharp** [comment]
@DanielNuttall-AD, @JoeBatt1989, @JHancox, @dbericat, @MMelQin 

As we've discussed this morning, we can still keep both Workload Manager (WM) & Task Manager (TM) in the same process for the first couple of releases. However, in the future, if we have a deployment as in the diagram, it's best to keep TM from accessing the database.  We can do this now to reduce the amount of refactoring when the time comes to separate the two and reduce technical debts.  This also simplifies database access controls at deploy time.

When a TM completes a task, it could simply emit an `md.tasks.complete` message along with the status.
When WM dispatches a new task, any data required, as defined by @joshliberty above, can be included in the message. If, for some reason, TM crashes, WM can also emit the same message for another TM to pick up the work.

Diagram illustrates 2 TMs + WM + IG running in different environments but all have access to the same 🐰 for message exchange.

![image](https://user-images.githubusercontent.com/4236590/161640782-e3451fb7-1a78-4e40-b8eb-0906f48cb33f.png)

**Comment by JHancox** [comment]
Thanks Victor – I see what you mean now and it seems to make sense to take this approach.

Best

Jonny

**Comment by mocsharp** [comment]
Here's a sequence diagram for Task Manager (for POC release) using a centralized event listener @joshliberty proposed.  

[![Task Manager](https://user-images.githubusercontent.com/4236590/162811127-3589f55f-a7ce-4746-a7ff-b1c5a73a4173.png)](https://sequencediagram.org/index.html#initialData=MQAgwgTgpghgLlAJieIAWc4AcDOAuAegJygEcBXKAOwGMkBLGAcwhgFsA6AewiYICg49OABsoIAOo8A1gDMRXAO4gAsjCrMoEEAFoQABQDyYfvywwIQmvXNU4LLuSwhgNRLJiIATJJnylquqaEGYWVjbqcCAARFIQcgrKahpMWtEoOJIqoZb01rZR0SpQODiaBhBcdDg86TCZKvo54QUxxaXlAIqUlAD8dQ2d-NSIpua5+ZEOTi6yNABGAIyyAOwgACr10oEpWs15EXYxmzjbycEDG9njLZExAIK8XAYi5Ez0VJf3TSOm+5N2abOYAAMTBIIAnBCQABRAAeCAgGhEIAAyloAG55Er8WRcOwwRQlLhscSyRY0AAMMQASjB5vNhCpOpd9Kjcfi4ITiaSQLJKTBqUUPgBJQyXAAiItRAGl-ocoo8mFxhlRRvLWmzTDAaEIMfBxOtsvwJCodMBFgA2SkAFkQlrwAGYAHxsvAGcjzET0HBoEogADUAYAVMGAORsRAcLmnDiIH3mOA0NBh0NB-hs81W232p3OxrumlQOj0DH+oOhiNRmPSOMJ+DJ1PBoMgKBluz8RpZ612h0u5nu7pQSiZCvhyPRrZ1nCJxtpgOt9twUwKLhYP78I06fOdd0SGDCTJ47Rt6hwHCdzrdnN951GwvFqCl-2njs6vUGq6mLd3lTugBqMDeogBqZKSHSpNqIhRBaAAcACsMArNSND1OIVaTrG8Yzg2Kbfmav7umAfo0NIR48Cg+r0CI9JiK2cLFuQQj4iA0A1OQEDVCAUEwTAjp2hCyCoSQrHEhxdCUQeQFelA+HbveIBFiQEBlpkUAMTQTH0CxbGOJxsk-gpAAyVSgSAABkIAfDgXJ2IwCCZDQ+KyPQTAcUgAA6VAQOQVBUFoICKMIaAgO87YgPcpRQGwXoAJ7dEB9AuUgABy7CyfwQEwYssHLMhIDCeIPl+QFeK+aMhl-iAADi1BaGZCBsFgPAWLFIA2S1qQFdAiBnowIgXpV7oilQwj9fQABe-rFf5IQ-t87rwoxCAABQAJTarqpaft8-DfNuC01XVrAOb48T+MojVYDRCCBawWBYHs+3Os6SpcO6RkwL5yb+oofiJJtH63W9e1PAdTyLRpTG-f9Sj4QAPDoh1Kc1VAkPwvXvttwNNJuZoWj2uYum6EWkZkGE1tOs4pouZ549evZ5iT6JquTE6U04IEIGGtNHEFcAhTZ8DkOT9w0HQWAIIgYamFAA3iIVrG+bNIBUFwURlWqckEzeTOou6aVkyAFNTth1M86+UQrWrok6BQw5QBtW464zxP62iIxs9WU6cwaFtLoFwXtVycAi8b0AAFbFnAPPqMg0D1CxYY0srWgperqJOM1lhIDLqrqnLImKzb6nLdpVCiex+mSdRtHiPTLtE667uG2Rxvs6b9ZJjTlsgCt0B2z0jv04RaJiFAuCy1rwzywVaHt1GM1aBwTlNWI3Pa9mrvN+6LOIF7mG1r73O81E-OCyHYdhjg5Di1ASC5yAFFhh41HuTzI8KUWYhoWpUPMRXXS4kMqFwVvPD4+pgIgHAmUSCm9Ca3hJq3A+lMza4X9mePuNsB720oE7fGW8m7M09gvQ+HBj5QAwXzIOQtQ7k0jtHWOapRKJwrmGEakD6CIHaLAyhU91SYy2vqW6RpTBvQZkQ92hgqBgBJNdKACAAASXAuDSHdCQVmgYQzjkXqnCAK85Hr0ofODGsAhE7SeKYTMjdbwFkUo+Z8o5tEYSXvo1e8jubzlPp2fQEjbG7hAEOEcWjKwTlcQYteCjjHNgXJbP4gigaGmyCMFwq4sBAA)

**Comment by mocsharp** [comment]
Update to the original description:

### Overview

The task manager is the subcomponent responsible for executing workflow tasks. It's responsible for triggering the task plug-ins, mapping input and output, providing metadata, and notifying the workflow manager after a task has been completed with output metadata and task status.

This task is concerned with the initial basic functionality of dispatching a task that has been added to the queue. Please see the following tickets for additional functionality:

- #47 
- #50 

### Monitoring of Events

The Task Manager subscribes to the following events:

1. `md.tasks.dispatch` is emitted by Workflow Manager to dispatch a task for execution with the external orchestration services.
2. `md.tasks.callback` is emitted by the external orchestration services when the task completes - #47 

#### Dispatching tasks - `md.tasks.dispatch`
Tasks are picked up from a queue in a RabbitMQ.
Queue name: md.tasks.dispatch
Type: `TaskDispatchEvent`
Event schema: 

```
{
  "correlation_id": "d1ffa435-1582-4aaa-8cab-912d86fb7e38",
  "execution_id": "91a70c2a-4a97-4103-a9a5-c77aed9f4d2a",
  "inputs": [
    {
      "bucket": "monaideploy",
      "credentials": {
        "access_key": "key",
        "access_token": "token"
      },
      "endpoint": "8.8.6.6",
      "name": "input-dicom",
      "relative_root_path": "/e08b7d7d-f30c-4f31-87d5-8ce5049aa956/dcm",
      "secured_connection": false
    },
    {
      "bucket": "monaideploy",
      "credentials": {
        "access_key": "key",
        "access_token": "toekn"
      },
      "endpoint": "8.8.6.6",
      "name": "input-ehr",
      "relative_root_path": "/e08b7d7d-f30c-4f31-87d5-8ce5049aa956/ehr",
      "secured_connection": false
    }
  ],
  "metadata": {},
  "outputs": [
    {
      "bucket": "monaideploy",
      "credentials": {
        "access_key": "key",
        "access_token": "token"
      },
      "endpoint": "10.105.3.254",
      "name": "tempStorage",
      "relative_root_path": "/rabbit",
      "secured_connection": false
    }
  ],
  "status": "Unknown",
  "task_assembly_name": "Monai.Deploy.WorkflowManager.TaskManager.Argo.ArgoPlugin, Monai.Deploy.WorkflowManager.TaskManager.Argo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "task_id": "caa10114-db70-4655-8b5d-273e16833c03",
  "task_plugin_arguments": {
    "baseUrl": "http://localhost:2746/",
    "workflowTemplateName": "list-input-artifacts-template",
    "workflowTemplateTemplateRefName": "s3-artifacts-template"
  },
  "workflow_id": "65666477-a775-4914-825b-5ecc33d0d6b4"
}
```
#### Handling a Task

Pre-requisite: An `md.tasks.dispatch` message contains all relevant information and arguments for the Task Manager to dispatch a job to the task plugin and external orchestration service.

1. Validate incoming message
2. Reserve execution resource
3. Check the task type and instantiate the relevant plug-in
4. Provide the following information to the specific plug-in:
    1. Storage input and output mapping & credentials.
    3. The `task_plugin_arguments` property (detail requirements are described in the relevant plugin GitHub issue)
    5. Output directory path
6. Call the plug-in's "Execute()" method
7. Send `md.tasks.update` with status `Accepted`
8. Acknowledge the task dispatch event so that it is removed from RabbitMQ

#### Plug-in Design

`ITaskPlugin` interact and `TaskPluginBase` are provided to implement a new task execution plug-in with the following methods:

1. `Task<ExecutionStatus> ExecuteTask(CancellationToken cancellationToken = default);`
    `ExecuteTask` is to execute the task with external orchestration service.  It should never throw any exceptions but return `ExecutionStatus` on completion or failures.
2. `Task<ExecutionStatus> GetStatus(string identity, CancellationToken cancellationToken = default)`
   `GetStatus` is called when a `md.tasks.callback` event is received to retrieve details status, metadata and artifacts of a completed (success or failed) task.

Each instance of the plug-in instantiated is passed along with the following:

- `IServiceScopeFactory`: service scop factory to get additional injects services
- `ILogger<ArgoPlugin>`: logger
- `TaskDispatchEvent`: dispatch event as describe in previous section


#### Plug-in Errors

A plug-in can fail either because the event doesn't contain the information it needs, or because of an external reason such as an app server not being available. To facilitate error handling plug-in should be able to raise one of the following exceptions:

- `InvalidTaskException`: to be used when the task does not contain the necessary information, for example when the task plug-in arguments don't contain the required fields for that plug-in.  This is thrown when constructing an instance of the plug-in.


### Acceptance criteria

- Given a valid event in RabbitMQ, when it is picked up by the event broker adapter it should trigger the task executer
- Given an event doesn't include all of the required information, when it is picked up by the event broker adapter it should be rejected with `requeue=false`
- When no resource is available to execute the plugin, the message should be rejected with `requeue=true`
- When the plug-in throws an invalid event exception or failed to instantiate, the message should be rejected with `requeue=false`
- When the plug-in's `Execute` method throws an exception (which it shouldn't have), the message should be rejected with `requeue=false`

Additional messaging handling requirements are to be defined in #100

**Comment by mocsharp** [comment]
@joshliberty please review the comment above.

**Comment by joshliberty** [comment]
@mocsharp all in all I'm okay with these changes, but I have a few notes:

1. Your description makes a change to the task dispatch event. This will need changing in more tickets, specifically those where the workflow executer is dispatching a task.
2. Your new task dispatch event schema contains the specific plug-in class. This doesn't make sense if we eventually want to separate workflow executer in the task manager to handle separate concerns. It makes more sense to have the plug-in name, and then map the name to a class in the task executer configuration.
3. Finally, a question – why do you have meta data in the task dispatch event? What is it going to be used for?

**Comment by jackschofield23** [comment]
One other point is that when we create temporary MinIO credentials, an access token, access key AND a session token are required. I will update the messaging repo with this change, so the credentials object will look like this:

`"credentials": {
        "access_key": "key",
        "access_token": "token",
        "session_token": "sessiontoken"
  },`

**Comment by mocsharp** [comment]
@joshliberty 

As we've discussed, I will update the `TaskDispatchEvent` to remove the credentials and have Task Manager generate the temporary credentials to access the storage service.

We will store credentials required to generate credentials in a config file for now.

1. The [changes ](https://github.com/Project-MONAI/monai-deploy-messaging/pull/7) were reviewed and approved previously.
2. I can move this mapping into Task Manager but the `TaskDispatchEvent` must still include the name of the plugin to activate.
3. For `metadata` I remember somewhere or sometime we mentioned passing metadata from one job to a downstream job.  We can remove it if that's not required.

**Comment by elleyouseewhy** [comment]
ROADMAP ESTIMATE: 6 Days
ACTUAL:
